Data gen comb
dw-innovation/kid2-spot pull request #7
Opened 2024-04-30 09:42 UTC by isspek

2024-04-30 16:17 UTC, dendelyne requested changes
Looks good in general, but I found some errors that need to fixed in the outputs of the three main scripts (combination retrieval, query generator, prompt generator). I added comments about the findings at the beginning of each file. Please have a look!

2024-04-30 16:17 UTC, dendelyne commented on scripts/datageneration/retrieve_combinations.py
I checked the output of the file, and the  resulting tag_combinations_vX.jsonl contains a lot of duplicate combination tags.

One example where e.g. "addr:street" is duplicated: 
`{"cluster_id": 30, "descriptors": ["cambio", "savings", "financial institution", "bank"], "comb_type": "core", "tags": [{"key": "amenity", "operator": "=", "value": "bureau_de_change"}, {"key": "amenity", "operator": "=", "value": "bank"}], "tag_attributes": [{"descriptors": ["building number", "house number"], "tags": [{"key": "addr:housenumber", "operator": "~", "value": "***any***"}]}, {"descriptors": ["street name"], "tags": [{"key": "addr:street", "operator": "~", "value": "***any***"}]}, {"descriptors": ["name"], "tags": [{"key": "name", "operator": "~", "value": "***any***"}]}, {"descriptors": ["height"], "tags": [{"key": "height", "operator": "=", "value": "***numeric***"}]}, {"descriptors": ["building levels", "floors"], "tags": [{"key": "building:levels", "operator": "=", "value": "***numeric***"}]}, {"descriptors": ["building number", "house number"], "tags": [{"key": "addr:housenumber", "operator": "~", "value": "***any***"}]}, {"descriptors": ["street name"], "tags": [{"key": "addr:street", "operator": "~", "value": "***any***"}]}, {"descriptors": ["brand"], "tags": [{"key": "brand", "operator": "~", "value": "***any***"}]}, {"descriptors": ["name"], "tags": [{"key": "name", "operator": "~", "value": "***any***"}]}]}`

Categories with more combinations (e.g. highway) result in extremely long lists of tags. I guess the duplicate remover needs to be checked.

2024-04-30 16:17 UTC, dendelyne commented on scripts/datageneration/generate_combination_table.py
I looked at the output and I noticed a few things:
- The "number_of_entities_in_prompt" is currently set to a fixed value. This means that you would need to generate a separate dataset for each number of entities and then merge them at the end for training. That seems really inefficient. It would be better to have a different system, like a maximum value of entities in a prompt, or a number of combinations to be generated for each number of prompts individually. There needs to be some rules with regards to the number of entities, since generating tons of examples with one or two entities does not help (as they can only represent a limited set of query types). Let's discuss how to solve this if you don't have a plan already! :)
- Every single entity is assigned at least one property. This is due to the way the entity selection works, as it does not include the option to have 0 properties (unless taginfo did not return any). This should be changed, as this will make the resulting sentences very convoluted. It would likely also not suffice to draw zero properties with the same probability as e.g. four. There needs to be a decent portion of entities without any properties, especially for cases with multiple entities. It is important to keep in mind that a sentence with many objects with multiple properties each becomes very convoluted, so the probability of different numbers of properties needs to be carefully selected. We can also brainstorm about this if you want.
- There are some attributes in the primary key list that are neither ***any***, nor ***numeric***. They do not require an operator or value. In the properties here however, they seem to be assigned a random value that is not related to the bundle (e.g. "{"name": "railway bridge", "operator": "=", "value": "loading_tower"}"). There is another case where operator and value are simply null (e.g. "{"name": "language school", "operator": null, "value": null}"). This should be fixed. In these cases, it should simply say {"name": "railway bridge"}, as the info about tags needs to be extracted from the taglist in a separate step. It looks like "null" values are handled by the prompt generator, but I wonder why we would keep these empty fields in the IMR, as it can only make it more difficult for the translation model with no added benefit. I would therefore just remove it.
- One question, do we know why we can't display special character? Is there a way to maybe use a different encoding in e.g. the output file that prevents this? (Example: "area": {"type": "area", "value": "Ca\u00f1ada de Benatanduz"})

2024-04-30 16:17 UTC, dendelyne commented on scripts/datageneration/gpt_data_generator.py
Here some comments:
- Before running this step, it appears that it is required to run the file "split_samples.py", which is not included in the pipeline and does not have a shell script. What is the advantage of doing that in general? Shouldn't it be just possible to generate data for the whole dataset at once? If this is a system to prevent a crash in the middle of the GPT sentence generation, I would advise to instead simple save the output after every timestep. That would however be easier than to force people to split it up into chunks if they don't want to.
- When "name" is selected, the regex selector always picks one of the variants "begins with", "ends with" or "contains". This would mean that there are no sentences generated where the query simply says "the name is..". This was fixed in an earlier version by simply adding a row of empty strings to the list of regex options. I am not sure why the error is back.

2024-04-30 16:17 UTC, dendelyne commented on scripts/datageneration/property_generator.py
- The way numeric values are currently selected is not ideal. It selects a random number from the range. If you want to cover the range from 0-99999 (which is our goal), this means that 90% of the time, the number will have 5 digits. This also means that the chance of drawing a single digit number is 0.0001%. It would be better to first select the number of digits (from 1-5), and then generate a random number of that length. This error applies to both functions that select numbers (decimal with metric and integer).

2024-04-30 16:17 UTC, dendelyne commented on scripts/datageneration/gpt_data_generator.py
> +        self.name_regex_templates = ["contains the letters", "begins with the letters", "ends with the letters"]
One way to fix the error that currently there is no "name is" version for prompting is to add three empty strings here. There even is code that supports this (line 227: "if len(entity_property.value) > 1 and len(selected_name_regex) > 0:" -> only select a a part of the string if regex is not empty string).

2024-04-30 16:49 UTC, isspek commented on scripts/datageneration/retrieve_combinations.py
thanks. I will report it as bug and fix it in the new repo, if you agree

2024-04-30 16:56 UTC, isspek commented on scripts/datageneration/generate_combination_table.py
1- we can add line 162. But let's do brainstorming on 1 and 2.
2- that is because of datamodel, I believe. We can remove them the final IMR, but i would keep in the previous stages.
3- this is unicode encoding. When we train t5, it will use this version anyway. We did like this before and frontend can handle this.

2024-04-30 16:58 UTC, isspek commented on scripts/datageneration/gpt_data_generator.py
1- I got crashes and wanted not to pay money for failures. We can write it as bug and investigate it.
2- i will add empty string, removed it mistakenly.

2024-04-30 16:58 UTC, isspek commented on scripts/datageneration/property_generator.py
to be honest, I haven't worked on this, this is from early version. I can check it as bug.

2024-05-13 11:51 UTC, dendelyne commented
Moved to https://github.com/dw-innovation/kid2-spot-datageneration. Issues related to data generation will be handled there. 

Issue/Pull request implementing these comments: https://github.com/dw-innovation/kid2-spot-datageneration/issues/1

2024-05-13 11:51 UTC, closed without merging